remote_theme: pmarsceill/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/xloot-mc.png"

# Color scheme supports "light" (default) and "dark"
color_scheme: dark
