remote_theme: pmarsceill/just-the-docs
logo: "https://avatars.githubusercontent.com/u/96182732?s=400&u=2e9bb86432a6069b9b4d4e862c53612934897b95&v=4"
color_scheme: dark
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Discussion":
    - "https://github.com/xloot-mc/xloot-mc.github.io/discussions"
  "YouTube":
    - "https://youtube.com/channel/UC2Ep5yOnfwSLRDOfN6k6mFA?sub_confirmation=1"

aux_links_new_tab: true
