remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/xloot-mc.png"
color_scheme: dark
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Discussion":
    - "https://github.com/xloot-mc/xloot-mc.github.io/discussions"
  "YouTube":
    - "https://youtube.com/channel/UC2Ep5yOnfwSLRDOfN6k6mFA?sub_confirmation=1"

aux_links_new_tab: true
